#!/bin/sh

cd ~

# Theming
export XCURSOR_SIZE=24

# XDG
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache

# Grk
export GTK2_RC_FILES="XDG_CONFIG_HOME"/gtk-2.0/gtkrc

# QT Applicaitons
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct

# Toolkit
export GDK_BACKEND="wayland"
export CLUTTER_BACKEND="wayland"
export _JAVA_AWT_WM_NONREPARENTING=1

exec Hyprland
